### PR TITLE
Portability fixes to compile on FreeBSD 9.1 w/ gcc 4.2.1

### PR DESCRIPTION
**Pull request by nathanweeks**
This addresses a couple issues that occur when building on FreeBSD 9.1 with the stock gcc 4.2.1:
1.  "-ansi" causes "Options.cpp:204: error: 'strtoull' was not declared in this scope" errors, since it apparently disables some support for data type "long long", which wasn't standardized until C++11. It's unlikely that "-ansi" implies C++11 on even the most recent versions of g++, so a reasonable alternative seems to be "-pedantic -Wno-long-long".
2. I observed the following errors:

```
Fasta.cpp: In member function 'void CFasta::Open(const std::string&)':
Fasta.cpp:259: error: conditional expression between distinct pointer types 'gzFile_s*' and 'FILE*' lacks a cast
Fasta.cpp:261: error: conditional expression between distinct pointer types 'gzFile_s*' and 'FILE*' lacks a cast
Fasta.cpp:267: error: conditional expression between distinct pointer types 'gzFile_s*' and 'FILE*' lacks a cast
Fasta.cpp:269: error: conditional expression between distinct pointer types 'gzFile_s*' and 'FILE*' lacks a cast
```

A cast in the macro so so it evaluated to a single type appeared necessary with this version of gcc, probably due to the issue described here: http://stackoverflow.com/questions/3833736/why-would-i-need-conversion

### CODE REVIEW

**Comment by CarlosBorroto** [comment]
Just to report I was hit by "2." on Debian Wheezy with gcc 4.7.2. I can confirm applying "08431bc" fix the issue.
